version: '3'
services:
  db:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
  app:
    container_name: coin_calculator
    image: coincalculator:v1
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
